### ISSUE TITLE
Viteにおけるalias Path設定が上手くいかない

### ISSUE THREAD

**Issue by Yuisei-Maruyama** [Yuisei-Maruyama/MyPortfolio_Vite_Vue#1]
[vite-tsconfig-paths](https://www.npmjs.com/package/vite-tsconfig-paths) を使用して、vite の alias に tsconfig.json の alias を読み込めるようにできると記載されていたが
上手く解釈されない模様・・・

(tsconfig.json)
```json
{
  "compilerOptions": {
    "baseUrl": ".", /* Base directory to resolve non-absolute module names. */
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
  },
}
```

(vite.config.ts)
```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { resolve } from 'path'
import env from 'vite-plugin-env-compatible'
import tsconfigPaths from 'vite-tsconfig-paths';

const pathSrc = resolve(__dirname, "./src")

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), env(), tsconfigPaths()],
  css: {
    preprocessorOptions: {
        scss: {
            additionalData: `@import "${pathSrc}/assets/scss/main.scss";`,
        },
    },
  }
})
```

(エラー)
```ts
he and forcing full-reload to ensure typescript is compiled with updated config values.
Failed to resolve import "@/pages/Home.vue" from "src/App.vue". Does the file exist?
0:33:19 [vite] Internal server error: Failed to resolve import "@/pages/Home.vue" from "src/App.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/y_metro/Develop/MyPortfolio_Vite_Vue/src/App.vue
  1  |  import { defineComponent as _defineComponent } from "vue";
  2  |  import Home from "@/pages/Home.vue";
     |                    ^
  3  |  const _sfc_main = /* @__PURE__ */ _defineComponent({
  4  |    __name: "App",
      at formatError (/Users/y_metro/Develop/MyPortfolio_Vite_Vue/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39055:46)
      at TransformContext.error (/Users/y_metro/Develop/MyPortfolio_Vite_Vue/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39051:19)
      at normalizeUrl (/Users/y_metro/Develop/MyPortfolio_Vite_Vue/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:58329:26)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (/Users/y_metro/Develop/MyPortfolio_Vite_Vue/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:58478:57)
      at async Object.transform (/Users/y_metro/Develop/MyPortfolio_Vite_Vue/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39292:30)
      at async doTransform (/Users/y_metro/Develop/MyPortfolio_Vite_Vue/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:50012:29)
```

**Comment by Yuisei-Maruyama** [comment]
別のアプローチとして、`vite.config.ts` に alias を設定することで設定を実現した！  

```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { resolve } from 'path'
import env from 'vite-plugin-env-compatible'

const pathSrc = resolve(__dirname, "./src")

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), env()],
  resolve:{
    alias: [
      {
        find: '@', replacement: pathSrc
      }
    ]
  },
  css: {
    preprocessorOptions: {
        scss: {
            additionalData: `@import "${pathSrc}/assets/scss/main.scss";`,
        },
    },
  }
})
```
